// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7ijdgNYARAkeqP9Kl_cFgSajxX6YOhg0',
    appId: '1:113268640510:web:5b5d34fd27132de1f0f3af',
    messagingSenderId: '113268640510',
    projectId: 'guideaut-2f025',
    authDomain: 'guideaut-2f025.firebaseapp.com',
    databaseURL: 'https://guideaut-2f025-default-rtdb.firebaseio.com',
    storageBucket: 'guideaut-2f025.appspot.com',
    measurementId: 'G-03MDR5E74P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg9VbvXP62CNQpHYGxNvuy71HE9Wp6OTs',
    appId: '1:113268640510:android:ac0a1fe1ae8e8a0cf0f3af',
    messagingSenderId: '113268640510',
    projectId: 'guideaut-2f025',
    databaseURL: 'https://guideaut-2f025-default-rtdb.firebaseio.com',
    storageBucket: 'guideaut-2f025.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7czXy3gfNY0-bX1Z0C6yNFLlSkaaohrg',
    appId: '1:113268640510:ios:8c7928bbde59eb99f0f3af',
    messagingSenderId: '113268640510',
    projectId: 'guideaut-2f025',
    databaseURL: 'https://guideaut-2f025-default-rtdb.firebaseio.com',
    storageBucket: 'guideaut-2f025.appspot.com',
    iosClientId: '113268640510-emtdg48kt85epq0s62ok55vuikcar0kn.apps.googleusercontent.com',
    iosBundleId: 'com.example.guidealt',
  );
}
